- name: apt-get update
  apt: update-cache=yes

- name: setup nodejs
  apt: pkg=nodejs force=yes install_recommends=yes

- name: setup npm
  apt: pkg=npm force=yes install_recommends=no

- name: install recli npm package
  npm: name=recli global=yes

- name: copy cron for unassigning stf devices
  template: src=roles/rethinkdb_client/templates/{{ item.file }} dest=/{{ item.file }} owner=root group=root mode={{ item.mode }}
  with_items:
    - { file: 'etc/cron.daily/unassign_stf_devices', mode: '775' }
